### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by djdoz** [ndf-zz/fv1build#1]
I'm trying to create a bank from the example folder using the make command  (see below), and it's giving me the below error.

djdoz@ubuntu:~/source/fv1build/example$ make
asfv1 -n -b 3_regacc.asm 3_regacc.prg
usage: asfv1 [-h] [-q] [-v] [-c] [-s] [-p {0,1,2,3,4,5,6,7}] [-b] infile outfile
asfv1: error: unrecognized arguments: -n
make: *** [Makefile:113: 3_regacc.prg] Error 2
djdoz@ubuntu:~/source/fv1build/example$

**Comment by ndf-zz** [comment]
Ah yes, option '-n' was removed a while back. Remove that from your ASFLAGS and it should be ok. Thanks for the info.
